import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Nav from "../components/Nav"
import { Footer } from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "TicketHub",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			
			<body
				className={
					inter.className +
					"justify-center bg-sky-300  "
				}>
					<Nav/>
				<div className="">{children}</div>
					<Footer/>
			</body>
		</html>
	)
}
