import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Nav from "../components/Nav"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "TicketHub",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={
					inter.className +
					" flex justify-center bg-slate-300 min-h-screen"
				}>
				<div className="container">{children}</div>
			</body>
		</html>
	)
}
